{{- if and (.Capabilities.APIVersions.Has "jenkins.io/v1/Release") (hasKey .Values.jx "releaseCRD") (.Values.jx.releaseCRD)}}
apiVersion: jenkins.io/v1
kind: Release
metadata:
  creationTimestamp: "2021-03-29T08:52:21Z"
  deletionTimestamp: null
  name: '{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}'
spec:
  commits:
  - author:
      email: v.behar@free.fr
      name: Vincent Behar
    branch: master
    committer:
      email: v.behar@free.fr
      name: Vincent Behar
    message: |
      chore: grafana postgres datasource should be configurable

      from the chart values
    sha: 35f49480a3e42050b881aac6b7fe47696cb6f4ad
  - author:
      email: james.strachan@gmail.com
      name: James Strachan
    branch: master
    committer:
      email: james.strachan@gmail.com
      name: James Strachan
    message: |
      chore: disable arm 32 bit for now
    sha: e6146a05c97e31e3e7a053811ef956ee9fa61588
  gitHttpUrl: https://github.com/jenkins-x/cd-indicators
  gitOwner: jenkins-x
  gitRepository: cd-indicators
  name: '{{ .Chart.Name }}'
  version: 0.0.5
status: {}
 
{{- end }}
