{{- if and (.Capabilities.APIVersions.Has "jenkins.io/v1/Release") (hasKey .Values.jx "releaseCRD") (.Values.jx.releaseCRD)}}
apiVersion: jenkins.io/v1
kind: Release
metadata:
  creationTimestamp: "2021-04-29T09:08:48Z"
  deletionTimestamp: null
  name: '{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}'
spec:
  commits:
  - author:
      email: v.behar@free.fr
      name: Vincent Behar
    branch: master
    committer:
      email: v.behar@free.fr
      name: Vincent Behar
    message: |
      fix: collect releases from lighthouse events

      because releases CRD are deprecated and not always generated

      Signed-off-by: Vincent Behar <v.behar@free.fr>
    sha: 6d8c659edde9313f8c2b114168e373a6b495112e
  gitHttpUrl: https://github.com/jenkins-x/cd-indicators
  gitOwner: jenkins-x
  gitRepository: cd-indicators
  name: '{{ .Chart.Name }}'
  version: 0.0.11
status: {}
 
{{- end }}
