apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cdindicators.fullname" . }}-postgresql-password
  labels:
    {{- include "cdindicators.labels" . | nindent 4 }}
stringData:
  postgresql-password: {{ .Values.postgresql.postgresqlPassword }}
