apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cdindicators.fullname" . }}
  labels:
    {{- include "cdindicators.labels" . | nindent 4 }}
stringData:
  postgresql-host: {{ if .Values.postgresql.useInternalInstance }}{{ include "cdindicators.fullname" . }}-postgresql.{{ .Release.Namespace }}{{ else }}{{ .Values.postgresql.postgresqlHost }}{{ end }}
  postgresql-port: {{ if .Values.postgresql.useInternalInstance }}5432{{ else }}{{ .Values.postgresql.postgresqlPort }}{{ end }}
  postgresql-database: {{ .Values.postgresql.postgresqlDatabase }}
  postgresql-username: {{ .Values.postgresql.postgresqlUsername }}
  postgresql-password: {{ .Values.postgresql.postgresqlPassword }}
