apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cdindicators.fullname" . }}-datasource
  labels:
    {{- include "cdindicators.labels" . | nindent 4 }}
    {{ .Values.grafana.datasources.label }}: {{ .Values.grafana.datasources.value | quote }}
stringData:
  postgres.yaml: |-
    apiVersion: 1
    datasources:
      - name: Indicators
        uid: indicators
        type: postgres
        url: {{ if .Values.postgresql.useInternalInstance }}{{ include "cdindicators.fullname" . }}-postgresql:5432{{ else }}{{ .Values.postgresql.postgresqlHost }}:{{ .Values.postgresql.postgresqlPort }}{{ end }}
        database: {{ .Values.postgresql.postgresqlDatabase }}
        user: {{ .Values.postgresql.postgresqlUser }}
        secureJsonData:
          password: {{ .Values.postgresql.postgresqlPassword }}
        jsonData:
          sslmode: disable
          maxOpenConns: 10
          maxIdleConns: 2
          connMaxLifetime: 14400
          postgresVersion: 1200
